# Generated by Django 2.2.4 on 2019-08-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLEntry',
            fields=[
                ('url', models.URLField()),
                ('slug', models.CharField(blank=True, max_length=6, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
